@Qilma_API_HostAddress = http://localhost:5164

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMyIsIk5hbWUiOiJBZnJhbSBIYXJvdW4iLCJFbWFpbCI6ImFmcmFtaGFyb25AaG90bWFpbC5jb20iLCJBZ2UiOiIyNiIsImlzcyI6IlFpbG1hQVBJIiwiYXVkIjoiUWlsbWFBUElVc2VycyJ9.OkGoUj7LLD2IJR5cLV_rZ6VzHLpKq39eI4Xx7Xo_rjo

@invalidToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiI0IiwiTmFtZSI6IkFmcmFtIEhhcm91biIsIkVtYWlsIjoiYWZyYW1oYXJvbkBob3RtYWlsLmNvbSIsIkFnZSI6IjI2IiwiaXNzIjoiUWlsbWFBUEkiLCJhdWQiOiJRaWxtYUFQSVVzZXJzIn0.zn0oT7tEQjTd6hroFYV2geG4-3Qakme-Jbrnu0v8ZvQ

GET {{Qilma_API_HostAddress}}/users/me
Authorization: Bearer {{invalidToken}}

###

PUT  {{Qilma_API_HostAddress}}/users/me
Authorization: Bearer {{invalidToken}}
Content-Type: application/json

{
    "name": "",
    "age": 2,
    "email": ""
}

###

DELETE {{Qilma_API_HostAddress}}/users/me
Authorization: Bearer {{invalidToken}}

###

PUT  {{Qilma_API_HostAddress}}/users/me/password
Authorization: Bearer {{invalidToken}}
Content-Type: application/json

{
    "currentPassword": "@Fram12345",
    "newPassword": "@Fram12345",
    "confirmPassword": "@Fram12345"
}

###

POST {{Qilma_API_HostAddress}}/games
# Authorization: Bearer {{token}}
# X-Guest-Id: 4

###

POST  {{Qilma_API_HostAddress}}/games/16/guess
# Authorization: Bearer {{token}}
# X-Guest-Id: 4
Content-Type: application/json

{
    "word": ""
}

###

GET {{Qilma_API_HostAddress}}/users/me/statistics
Authorization: Bearer {{token}}